- src/main/kotlin/codel/auth/business/AuthService.kt
- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/domain/Member.kt
- src/main/kotlin/codel/member/domain/MemberRepository.kt
- src/main/kotlin/codel/member/domain/Profile.kt
- src/main/kotlin/codel/member/infrastructure/entity/MemberEntity.kt
- src/main/kotlin/codel/member/infrastructure/entity/ProfileEntity.kt
- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/request/MemberLoginRequest.kt
- src/main/kotlin/codel/member/presentation/response/MemberLoginResponse.kt
- src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
- src/test/kotlin/codel/config/TestFixture.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
- src/test/kotlin/codel/member/infrastructure/MemberJpaRepositoryTest.kt
- src/test/kotlin/codel/member/presentation/MemberControllerTest.kt
도메인과 엔티티의 기본값과 초기화 위치 변경
- close #13 
도메인과 엔티티의 기본값과 초기화 위치 변경
> [refactor/#13] 도메인과 엔티티의 기본값과 초기화 위치 변경

- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/domain/Member.kt
- src/main/kotlin/codel/member/domain/MemberRepository.kt
- src/main/kotlin/codel/member/infrastructure/entity/MemberEntity.kt
- src/main/kotlin/codel/member/infrastructure/entity/ProfileEntity.kt
- src/test/kotlin/codel/auth/TokenProviderTest.kt
- src/test/kotlin/codel/config/TestFixture.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
- src/test/kotlin/codel/member/domain/MemberRepositoryTest.kt
- src/test/kotlin/codel/member/infrastructure/MemberJpaRepositoryTest.kt
코드 프로필 이미지 저장 로직 구현
- close #17 
1. 프론트에서 MultiPartFile을 받는다.
2. MultiPartFile 을 s3와 통신하여 저장한다.
3. 저장한 url을 받아 db에 저장한다.
> 코드 프로필 이미지 저장 로직 구현

- build.gradle.kts
- src/main/kotlin/codel/auth/TokenProvider.kt
- src/main/kotlin/codel/auth/business/AuthService.kt
- src/main/kotlin/codel/config/S3Config.kt
- src/main/kotlin/codel/config/WebMvcConfig.kt
- src/main/kotlin/codel/config/argumentresolver/LoginMember.kt
- src/main/kotlin/codel/config/argumentresolver/MemberArgumentResolver.kt
- src/main/kotlin/codel/config/filter/JwtAuthFilter.kt
- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/domain/ImageUploader.kt
- src/main/kotlin/codel/member/domain/Member.kt
- src/main/kotlin/codel/member/domain/MemberRepository.kt
- src/main/kotlin/codel/member/domain/S3Uploader.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
- src/main/kotlin/codel/member/infrastructure/S3Uploader.kt
- src/main/kotlin/codel/member/infrastructure/entity/MemberEntity.kt
- src/main/kotlin/codel/member/infrastructure/entity/ProfileEntity.kt
- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/request/CodeImageSavedRequest.kt
- src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
- src/test/kotlin/codel/auth/TokenProviderTest.kt
- src/test/kotlin/codel/config/TestFixture.kt
- src/test/kotlin/codel/config/argumentresolver/MemberArgumentResolverTest.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
- src/test/kotlin/codel/member/domain/MemberRepositoryTest.kt
- src/test/kotlin/codel/member/infrastructure/MemberJpaRepositoryTest.kt
- src/test/kotlin/codel/member/presentation/MemberControllerTest.kt
코드 프로필 이미지 저장 로직 추가 및 프로필 저장 로직 수정
- close #15 
프로필 저장 로직 수정, 코드 프로필 이미지 저장 로직 추가, 테스트 작성
https://www.notion.so/API-1c1b731c33d080a69510dfdeefa1d048?p=1c1b731c33d081608677e91060d1b764&pm=s
https://www.notion.so/API-1c1b731c33d080a69510dfdeefa1d048?p=1c1b731c33d08152a4adfefafe2fa27c&pm=s
> [feature/#15] 코드 프로필 이미지 저장 로직 추가 및 프로필 저장 로직 수정

- build.gradle.kts
- src/main/kotlin/codel/config/filter/JwtAuthFilter.kt
spring actuator 의존성을 추가하고, 프로메테우스 정보수집 대기
- #22 
프로메테우스 연결을 위한 spring actuator 설정을 열어두었습니다. 
프로메테우스 연결을 위한 사전작업이라 일단 이번 pr 머지하고 이슈는 닫지 않겠습니다
> [feature/#22] spring actuator 설정

- .github/workflows/cd.yml
- .github/workflows/ci.yml
> [feature/#22] ci/cd 스크립트 파일 수정

- build.gradle.kts
prometheus 의존성 추가
- #22 
프로메테우스 의존성을 추가했습니다.
> [feature/#22] prometheus 의존성 추가

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- build.gradle.kts
logback appender 의존성 추가
- #22 
로키 설정을 위한 logback appender 의존성 추가
> [feature/#22] logback appender 의존성 추가

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .gitignore
- build.gradle.kts
- src/main/kotlin/codel/auth/exception/AuthException.kt
- src/main/kotlin/codel/config/FcmConfig.kt
- src/main/kotlin/codel/config/argumentresolver/MemberArgumentResolver.kt
- src/main/kotlin/codel/config/exception/CodelException.kt
- src/main/kotlin/codel/config/exception/GlobalExceptionHandler.kt
- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/domain/Member.kt
- src/main/kotlin/codel/member/domain/MemberRepository.kt
- src/main/kotlin/codel/member/exception/MemberException.kt
- src/main/kotlin/codel/member/infrastructure/entity/MemberEntity.kt
- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/request/MemberLoginRequest.kt
- src/main/kotlin/codel/member/presentation/request/ProfileSavedRequest.kt
- src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
- src/main/kotlin/codel/notification/business/NotificationService.kt
- src/main/kotlin/codel/notification/business/request/NotificationRequest.kt
- src/main/kotlin/codel/notification/domain/Notification.kt
- src/main/kotlin/codel/notification/exception/NotificationException.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
- src/test/kotlin/codel/member/domain/MemberRepositoryTest.kt
- src/test/kotlin/codel/member/presentation/MemberControllerTest.kt
fcm을 알림구현과 도메인 로직으로 엔티티 변환
- close #28
fcm 을 통해 알림을 구현
기존 repository에서 엔티티의 변환 로직을 도메인을 통한 변경으로 수정
> Fcm 을 활용한 알림 구현

- .github/workflows/cd.yml
- src/main/kotlin/codel/auth/TokenProvider.kt
- src/main/kotlin/codel/auth/business/AuthService.kt
- src/main/kotlin/codel/config/Loggable.kt
- src/main/kotlin/codel/config/argumentresolver/MemberArgumentResolver.kt
- src/main/kotlin/codel/config/exception/GlobalExceptionHandler.kt
- src/main/kotlin/codel/config/filter/JwtAuthFilter.kt
- src/main/kotlin/codel/config/filter/MemberLoggingFilter.kt
- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/domain/MemberRepository.kt
- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/test/kotlin/codel/config/argumentresolver/MemberArgumentResolverTest.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
예외, 요청 상황에 로깅 출력 및 MDC 로깅 도입
- close #33 
info : 예측 가능한 커스텀 예외
warn : 예측 불가능한 예외
error : 프로그램이 종료될 정도의 에러
예외, 요청의 로깅의 중요한 점은 "누가 했냐" 라고 생각하여 MDC 로깅 도입
매 로그마다 자동으로 memberId 를 출력할 수 있도록 구현
> [feature/#33] 예외, 요청 상황에 로깅 출력 및 MDC 로깅 도입

- .github/workflows/cd.yml
> [feature/#30] 도커 배포 수정

- .github/workflows/cd.yml
docker 권한 문제 해결
- #30
docker 권한 문제 해결
> [feature/#30] docker 권한 문제 해결

- .github/workflows/cd.yml
- src/main/kotlin/codel/admin/presentation/AdminController.kt
log back 라밸 변경
타임리프 에러 수정
- #30
로그백 라벨 설정 수정
타임리프 html 절대 경로 -> 상대 경로
> [feature/#30] log back 라밸 변경

- .github/workflows/cd.yml
[##](url) PR의 목적이 무엇인가요?
로그 백 설정 수정
- #30
> [feature/#30] 로그 백 설정 수정

- src/main/kotlin/codel/admin/business/AdminService.kt
- src/main/kotlin/codel/member/domain/Member.kt
- src/main/kotlin/codel/member/infrastructure/entity/MemberEntity.kt
- src/main/kotlin/codel/member/presentation/request/MemberLoginRequest.kt
- src/main/resources/templates/home.html
- src/test/kotlin/codel/config/TestFixture.kt
- src/test/kotlin/codel/config/argumentresolver/MemberArgumentResolverTest.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
- src/test/kotlin/codel/member/domain/MemberRepositoryTest.kt
- src/test/kotlin/codel/member/infrastructure/MemberJpaRepositoryTest.kt
- src/test/kotlin/codel/member/presentation/MemberControllerTest.kt
멤버 도메인에 이메일 추가
- close #42 
- 멤버 도메인에 email 값을 추가했습니다.
- oauth 로그인시 dto에 email을 추가로 받습니다.
- 받은 이메일 값을 바탕으로 admin 페이지 수정했습니다.
> [feature/#42] 멤버 도메인에 이메일 추가

- src/main/kotlin/codel/member/presentation/request/MemberLoginRequest.kt
멤버 email nullable 수정
- close #44 
멤버 로그인 dto email nullable 수정
> [bug/#44] 멤버 email nullable 수정

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .gitignore
- src/main/resources/logback-spring.xml
CI/CD 빌드 스크립트 수정
logback-spring.xml 파일 생성
- #48
> [chore/#45] CI/CD 빌드 스크립트 수정

- src/main/kotlin/codel/member/domain/OauthType.kt
구글 OAuth 추가하기
resolve #57 
구글 OAuth 추가
> [feature/#57] OAuthType에 구글 추가하기

- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
홈, 파도타기 멤버 조회시 회원가입 완료하지 않은 멤버가 노출될 수 있다.
- close #64 
쿼리에 memberStatus 값을 추가한다.
> [refactor/#64] 멤버 상태값 조건 추가

- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/response/MemberRecommendResponses.kt
- src/main/kotlin/codel/member/presentation/response/MemberResponse.kt
- src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
dto 공통화를 위해 네이밍을 변경한다.
- close #68 
api에 종속되지 않은 범용화된 dto를 만든다.
> [refactor/#68] dto 네이밍 변경

- src/main/kotlin/codel/signal/domain/Signal.kt
> [feature/#75] 시그널 도메인 생성

- src/main/kotlin/codel/chat/repository/ChatRepository.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
채팅 목록 조회 api 문제 수정
홈 findRandomMembersStatusDone 파라미터 바인딩 수정
resolve #79 
채팅 목록 조회 api 문제 수정
홈 findRandomMembersStatusDone 파라미터 바인딩 수정
그냥 제가 홈쪽 수정헀어요!
> [feature/#79] 채팅 정렬 수정, seed 파라미터 바인딩 수정

- .github/workflows/cd.yml
- src/main/kotlin/codel/signal/domain/Signal.kt
DDL Auto 값 변경을 통해 더미데이터 데이터 초기화 상황을 방지합니다.
- #82 
ddl-auto 값을 변경하여 더미데이터가 유지되게끔 합니다.
> [config] Github Action DDL Auto 값 변경

- src/main/kotlin/codel/member/presentation/response/MemberRecommendResponses.kt
> [refactor#88] : 배열 형태의 응답 데이터 일관성 수정

- src/main/kotlin/codel/signal/business/SignalService.kt
- src/main/kotlin/codel/signal/infrastructure/SignalJpaRepository.kt
- src/main/kotlin/codel/signal/presentation/SignalController.kt
- src/main/kotlin/codel/signal/presentation/response/SignalMemberResponse.kt
- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
보낸 시그널 목록 조회 기능 구현
- #96 
1. 보낸 시그널 API 구현
보낸 시그널 중 대기 중(PENDING) 상태만 조회합니다.
2. 보낸 시그널 API 테스트 코드 작성
> [feature/#96] 보낸 시그널 목록 조회

- src/main/kotlin/codel/signal/presentation/SignalController.kt
- src/main/kotlin/codel/signal/presentation/swagger/SignalControllerSwagger.kt
[docs/#102] SignalController Swagger 적용
- #102 
1. SignalController Swagger 적용
> [docs/#102] SignalController Swagger 적용

- src/main/kotlin/codel/signal/business/SignalService.kt
- src/main/kotlin/codel/signal/domain/Signal.kt
- src/main/kotlin/codel/signal/domain/SignalStatus.kt
- src/main/kotlin/codel/signal/presentation/SignalController.kt
- src/main/kotlin/codel/signal/presentation/swagger/SignalControllerSwagger.kt
- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
시그널 매칭성공 조회 API
- #110 
1. 시그널 매칭성공 조회 API
2. 매칭성공 시 상태 값 변경 ( ACCEPTED -> APPROVED / ACCEPTED_HIDDEN -> APPROVED_HIDDEN )
3. Swagger 문서화
> [feature/#110] 시그널 매칭성공 조회 API

- src/main/kotlin/codel/signal/presentation/SignalController.kt
- src/main/kotlin/codel/signal/presentation/response/SignalMemberResponse.kt
> [fix/#115] 수신/발신 시그널 조회 기능 수정

- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
> [fix] 테스트 수정

- src/main/kotlin/codel/member/domain/Profile.kt
- src/main/kotlin/codel/member/presentation/request/ProfileSavedRequest.kt
- src/main/kotlin/codel/member/presentation/response/MemberProfileResponse.kt
question / answer 필드 데이터 추가
- #125
> [feat] question / answer 필드 데이터 추가

- src/main/kotlin/codel/signal/presentation/SignalController.kt
- src/main/kotlin/codel/signal/presentation/swagger/SignalControllerSwagger.kt
Swagger 문서화 : getUnlockedSignal, hideSignal
- #129
Swagger 문서화 : getUnlockedSignal, hideSignal
> [docs#129] Swagger 문서화 : getUnlockedSignal, hideSignal

- src/main/kotlin/codel/signal/business/SignalService.kt
- src/main/kotlin/codel/signal/domain/Signal.kt
- src/main/kotlin/codel/signal/presentation/response/SignalResponse.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
> [refactor/#132] 시그널 코드 리팩토링

- src/main/kotlin/codel/signal/business/SignalService.kt
- src/main/kotlin/codel/signal/domain/Signal.kt
- src/main/kotlin/codel/signal/presentation/SignalController.kt
- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
sendSignal : 시그널 전송 시 메시지 포함
- #124
시그널 전송 시 상대방의 중요 질문에 대한 응답을 포함하여 넘길 수 있습니다.
> [feat] sendSignal : 시그널 전송 시 메시지 포함

- src/main/kotlin/codel/signal/business/SignalService.kt
- src/main/kotlin/codel/signal/domain/Signal.kt
- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
머지 충돌 해결
- #135
1. sendSignal 코드 수정
2. 테스트 코드 수정
> [fix/#135] 머지 충돌 해결

- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/response/MemberProfileDetailResponse.kt
- src/main/kotlin/codel/member/presentation/response/MemberProfileResponse.kt
- src/main/kotlin/codel/signal/domain/Signal.kt
- src/main/kotlin/codel/signal/domain/SignalStatus.kt
- src/main/kotlin/codel/signal/presentation/response/SignalMemberResponse.kt
- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
> [feature/#138] 멤버 상세 조회 API

- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
> [docs] 회원 상세 조회 API 문서화

- src/main/kotlin/codel/chat/business/ChatService.kt
- src/main/kotlin/codel/chat/domain/ChatRoom.kt
- src/main/kotlin/codel/chat/infrastructure/ChatJpaRepository.kt
- src/main/kotlin/codel/chat/presentation/ChatController.kt
- src/main/kotlin/codel/chat/presentation/request/ChatLogRequest.kt
- src/main/kotlin/codel/chat/presentation/response/ChatRoomResponse.kt
- src/main/kotlin/codel/chat/presentation/swagger/ChatControllerSwagger.kt
- src/main/kotlin/codel/chat/repository/ChatRepository.kt
- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
> [feature/#142] 채팅방 목록 조회 API 수정

- src/main/kotlin/codel/member/presentation/MemberController.kt
- src/main/kotlin/codel/member/presentation/swagger/MemberControllerSwagger.kt
> [fix] 머지 충돌 해결

- src/main/kotlin/codel/report/presentation/ReportController.kt
- src/main/kotlin/codel/report/presentation/swagger/ReportControllerSwagger.kt
> [docs] 신고하기 API 문서화

- src/main/kotlin/codel/block/presentation/swagger/BlockControllerSwggger.kt
> [docs] 문서화 수정

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- src/main/kotlin/codel/admin/business/AdminService.kt
- src/main/kotlin/codel/admin/presentation/AdminController.kt
- src/main/kotlin/codel/chat/infrastructure/ChatRoomJpaRepository.kt
- src/main/kotlin/codel/config/RestTemplateConfig.kt
- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/notification/business/NotificationService.kt
- src/main/kotlin/codel/notification/domain/Notification.kt
- src/main/kotlin/codel/notification/domain/NotificationType.kt
- src/main/kotlin/codel/notification/domain/sender/DiscordNotificationSender.kt
- src/main/kotlin/codel/notification/domain/sender/FcmNotificationSender.kt
- src/main/kotlin/codel/notification/domain/sender/NotificationSender.kt
- src/main/resources/templates/memberDetail.html
- src/test/kotlin/codel/config/TestFixture.kt
- src/test/kotlin/codel/member/business/MemberServiceTest.kt
> [feature/#153] 회원가입 알림기능 생성

- src/main/kotlin/codel/block/infrastructure/BlockMemberRelationJpaRepository.kt
- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
- src/main/kotlin/codel/signal/infrastructure/SignalJpaRepository.kt
차단된 회원을 조회하는 경우 제외하도록 수정
- #152
> [feature/#152] 차단된 회원을 조회하는 경우 제외하도록 수정

- .github/workflows/cd.yml
> [hotfix] cd.yml 수정

- .github/workflows/cd.yml
> [bug] docker 실행 시 JAVA_OPTS 값 추가

- src/main/kotlin/codel/signal/presentation/swagger/SignalControllerSwagger.kt
> [bug] Swagger 문서화 수정

- src/main/kotlin/codel/chat/presentation/swagger/ChatControllerSwagger.kt
> [docs] 채팅 문서화 수정

- src/main/kotlin/codel/signal/business/SignalService.kt
[feat] 시그널 수락 시 채팅방에 가장 최근 채팅(상대방의 답변) 저장하기
- #180
> [feat] 시그널 수락 시 채팅방에 가장 최근 채팅(상대방의 답변) 저장하기

- src/main/kotlin/codel/chat/presentation/ChatWebSocketController.kt
채팅 전송 시 소켓에서 내 채팅목록에도 채팅방 관련해 전송하도록 수정
- #190
> [feat] 채팅 전송 시 소켓에서 내 채팅목록에도 채팅방 관련해 전송하도록 수정

- src/main/kotlin/codel/chat/business/ChatService.kt
- src/main/kotlin/codel/signal/business/SignalService.kt
- src/main/kotlin/codel/signal/presentation/SignalController.kt
- src/test/kotlin/codel/signal/business/SignalServiceTest.kt
시그널 수락 시 채팅방 생성되었음을 소켓으로 전송
- #188
> [feat] 시그널 수락 시 채팅방 생성되었음을 소켓으로 전송

- src/main/kotlin/codel/chat/business/ChatService.kt
- src/main/kotlin/codel/chat/domain/ChatContentType.kt
- src/main/kotlin/codel/chat/presentation/ChatController.kt
- #197
이벤트 발행하는 소켓채널에서 어떤 데이터를 넘겨줘야할지 결정되어야 작업할 수 있을거라고 예상해서 TODO로 만들어두고 실시간채팅에 대한 이벤트는 상황은 미뤄두었습니다
> [feat] 코드해제 요청 시 시스템 메시지 생성 및 소켓으로 메시지 발행

- src/main/kotlin/codel/chat/domain/Chat.kt
- src/main/kotlin/codel/chat/presentation/response/ChatResponse.kt
채팅룸 렌더링 구분 데이터 ChatType -> memberId로 변경
- #221
> [bug] 채팅룸 렌더링 구분 데이터 ChatType -> memberId로 변경

- src/main/kotlin/codel/chat/business/ChatService.kt
- src/main/kotlin/codel/chat/business/CodeUnlockService.kt
- src/main/kotlin/codel/chat/domain/ChatRoom.kt
- src/main/kotlin/codel/chat/domain/ChatRoomMember.kt
- src/main/kotlin/codel/chat/domain/ChatRoomMemberStatus.kt
- src/main/kotlin/codel/chat/domain/ChatRoomStatus.kt
- src/main/kotlin/codel/chat/domain/CodeUnlockRequest.kt
- src/main/kotlin/codel/chat/domain/UnlockRequestStatus.kt
- src/main/kotlin/codel/chat/infrastructure/CodeUnlockRequestJpaRepository.kt
- src/main/kotlin/codel/chat/presentation/response/ChatRoomResponse.kt
> 채팅방 리스트 조회 시 상태 값 수정

- .github/workflows/cd.yml
- build.gradle.kts
- scripts/blue-green-deploy.sh
….sh 생성
[feat] 무중단 배포 cd.yml 수정 / health 체크를 위한 의존성 주석 제거 / blue-green-deploy.sh 생성
- close #220
> [feat] 무중단 배포 cd.yml 수정 / health 체크를 위한 의존성 주석 제거 / blue-green-deploy.sh 생성

- src/main/kotlin/codel/signal/infrastructure/SignalJpaRepository.kt
SignalRepository Question 테이블 조인해오도록 쿼리 수정
- close #242
> [bug/#242] SignalRepository Question 테이블 조인해오도록 쿼리 수정

- src/main/kotlin/codel/chat/business/ChatService.kt
- src/main/kotlin/codel/member/domain/MemberRepository.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
> [bug] ChatService Question Lazy Loading 문제 해결

- src/main/kotlin/codel/block/infrastructure/BlockMemberRelationJpaRepository.kt
- src/main/kotlin/codel/member/business/MemberService.kt
> Bug/#246 회원 실시간 차단 필터링 적용

- src/main/kotlin/codel/signal/infrastructure/SignalJpaRepository.kt
> [bug/#248] 받은 시그널 숨김 처리 시 적용되도록 수정

- src/main/kotlin/codel/admin/business/AdminService.kt
- src/main/kotlin/codel/admin/presentation/AdminController.kt
- src/main/kotlin/codel/question/business/QuestionService.kt
- src/main/kotlin/codel/question/domain/Question.kt
- src/main/kotlin/codel/question/infrastructure/QuestionJpaRepository.kt
- src/main/resources/templates/home.html
- src/main/resources/templates/memberList.html
- src/main/resources/templates/questionEditForm.html
- src/main/resources/templates/questionForm.html
- src/main/resources/templates/questionList.html
> [feat] 질문 관리 시스템

- src/main/kotlin/codel/admin/business/AdminService.kt
- src/main/kotlin/codel/admin/presentation/AdminController.kt
- src/main/kotlin/codel/member/business/MemberService.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
- src/main/resources/templates/home.html
- src/main/resources/templates/memberDetail.html
- src/main/resources/templates/memberList.html
관리자페이지 회원 관리 기능 리팩토링
- close #254
> Feature/#257 관리자페이지 회원 관리 기능 리팩토링

- src/main/kotlin/codel/chat/business/CodeUnlockService.kt
- src/main/kotlin/codel/chat/infrastructure/ChatJpaRepository.kt
- src/main/kotlin/codel/chat/infrastructure/ChatRoomMemberJpaRepository.kt
- src/main/kotlin/codel/chat/infrastructure/CodeUnlockRequestJpaRepository.kt
- src/main/kotlin/codel/chat/repository/ChatRepository.kt
- src/main/kotlin/codel/member/infrastructure/MemberJpaRepository.kt
Bug/#261 채팅 조회시 같은 채팅이 중복되서 반환되는 문제
- close #261 
채팅 조회시 같은 채팅이 중복되서 반환되는 문제
> Bug/#261 채팅 조회시 같은 채팅이 중복되서 반환되는 문제

- src/main/kotlin/codel/chat/business/ChatService.kt
- src/main/kotlin/codel/chat/presentation/ChatController.kt
> [feat] 채팅 종료 시 소켓채널에 메시지 반환하도록 수정
